### ISSUE TITLE
Question: Specify from witch level to start.

### ISSUE THREAD

**Issue by epiblue** [vladikk/JSON2CSV#2]
Hello,
I'm a begginer with this kind of operations, so please, forgive me for my ignorance.

I need a little help to convert the JSON file to CSV. 

Here's the structure that we have: 
`{
    "291785197178": 
    {
        "marketplace": "Spain",
        "identifiers": 
        {
            "item_id": 291785197178,
            "sku": "prestashop-248",
            "ean": "",
            "upc": "",
            "epid": "",
            "isbn": "",
            "brand_mpn": 
            {
                "brand": "",
                "mpn": ""
            }
        }
    }
}
`

Your code works, but it only gets the "291785197178" values, how cna I start from the 2nd or 3rd level? Is it posible? 

Thank you,

**Comment by vladikk** [comment]
Hi Artur,

Try wrapping your json object in an array:

[
  {
    "291785197178": {
      "marketplace": "Spain",
      "identifiers": {
        "item_id": 291785197178,
        "sku": "prestashop-248",
        "ean": "",
        "upc": "",
        "epid": "",
        "isbn": "",
        "brand_mpn": {
          "brand": "",
          "mpn": ""
        }
      }
    }
  }
]
