### ISSUE TITLE
CSV file has only what should be header row items

### ISSUE THREAD

**Issue by genfhk** [vladikk/JSON2CSV#4]
...and they're all in column A.

[Json-CSV_tests.zip](https://github.com/vladikk/JSON2CSV/files/509090/Json-CSV_tests.zip)

**Comment by belisards** [comment]
the same here

**Comment by stalane** [comment]
same

**Comment by vladikk** [comment]
The input file should either be an array of objects or a line delimited JSON file (line per object).
You can see examples in the tests/testcases folder.
