### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blanskiy** [vladikk/JSON2CSV#6]
Привет Владик, взял ваш json2csv file и пытался работать с ним, но выходит error: decoder.py  line 342 in decode raise JSONDecodeError("extra data",s , end) json.decoder.JSONDecoderError:Extra data: line 2 column 1 (char 1070)
Вы можете помочь?
Борис.
Email blanskiy@yahoo.com

**Comment by vladikk** [comment]
Странно. Какая у вас версия питона?
Вы уверены, что json валиден?

**Comment by blanskiy** [comment]
Спасибо за быстрый ответ, у меня 3.6 версия, кажется в самом Json есть extra space и это ведёт к ошибке. Могу дать json file воспроизвести ошибку.

**Comment by blanskiy** [comment]
Проверил json на https://Jason-cvs.com , конвертирует без ошибок...

**Comment by vladikk** [comment]
В этом и дело. Скрипт очень старый, писался под питон 2.7. Попробуйте запустить на 2.7. Если все равно не будет работать, пришлите файл, попробую посмотреть. 

Надо будет как нибудь переписать для третьего питона.

**Comment by blanskiy** [comment]
Кажется там всего 2 исправления. 1. Убрать Unicode он в 3 версии входит в str 
2. Эта ошибка кот я не смог пройти, начинающий в питоне, возможны для вас это можно починить быстро, кажется это связано с extra space. Буду благодарен за помощь.

**Comment by blanskiy** [comment]
Задача над кот работаю: создать pipeline aws сонвертирующая json log files into cvs and load it to mysql. Споткнулся на сонвертации и нашёл вашу программу.

**Comment by vladikk** [comment]
Там с поддержкой третьего питона немного сложнее, уже как-то пытался
доработать, но там разница в работе с массивами.
Можно посмотреть пример вашего json файла? Попробую еще раз.

**Comment by blanskiy** [comment]
Can I have your email address? will send you from my private email.

**Comment by blanskiy** [comment]
sorry, don't have russian script at work

**Comment by vladikk** [comment]
Sure - vladik@khononov.com

**Comment by blanskiy** [comment]
thank you, will send shortly

**Comment by blanskiy** [comment]
just sent, thank you for help, appreciate greatly.

**Comment by vladikk** [comment]
The project was ported to python3
